apiVersion: eksctl.io/vlalpha5
kind: Clusterconfig

metadata:
  name: expense-1
  region: us-east-1

manageNodeGroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true